name: Package lambda
description: Upload zip file to AWS Lambda, publish version and update alias

inputs:
  zip_path:
    required: false
    default: lambda.zip
    description: "Path of the packaged zip file"
  lambda_type:
    required: true
    description: "Lambda type (python | node)"


runs:
  using: "composite"
  steps:
    - name: Build lambda zip package
      shell: bash
      run: |
        rm -rf packaged-lambda ${{ inputs.zip_path }}
        mkdir -p packaged-lambda
        
        LAMBDA_TYPE=${{ inputs.lambda_type }}
        
        case $LAMBDA_TYPE in
          python)
            python -m pip install --upgrade pip
            python -m pip install -r lambda/python/requirements.txt -t packaged-lambda/
            cp -r lambda/python/src/* packaged-lambda/
            cp lambda/python/lambda_function.py packaged-lambda/
            ;;
          node)
            cp lambda/node/package.json packaged-lambda/
            cp lambda/node/package-lock.json packaged-lambda/
            cp -r lambda/node/dist packaged-lambda/
            cp -r lambda/node/node_modules packaged-lambda/
            ;;
          *)
            echo "❌ Unknown lambda_type: LAMBDA_TYPE"
            echo "Expected: python | node"
            exit 1
            ;;
        esac
        
        zip -r ${{ inputs.zip_path }} packaged-lambda